shopping_list = ['apples', 'oranges', 'melons']
print(shopping_list)
shopping_list.append('carrots')
shopping_list.remove('oranges')
print(shopping_list)
shopping_list.pop(0)
shopping_list.insert(1, 'apples')
print(shopping_list)
shopping_list.sort()
print(shopping_list)